# Generated by Django 4.1.3 on 2023-02-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('mobile_number', models.CharField(max_length=15)),
                ('size', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('product_images', models.ImageField(upload_to='product_images')),
            ],
        ),
    ]
